services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: kolo
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-store-network

  spring-boot-store:
    container_name: spring-store
    image: spring/store
    ports:
      - "8090:8090"
    networks:
      - spring-store-network
    depends_on:
      - postgres


volumes:
  postgres:

networks:
  spring-store-network:
    driver: bridge